# permissions for end users to view rokibulhasans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rokibulhasan-viewer-role
rules:
- apiGroups:
  - apiserver.my.crd
  resources:
  - rokibulhasans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiserver.my.crd
  resources:
  - rokibulhasans/status
  verbs:
  - get
