# permissions for end users to edit rokibulhasans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rokibulhasan-editor-role
rules:
- apiGroups:
  - apiserver.my.crd
  resources:
  - rokibulhasans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiserver.my.crd
  resources:
  - rokibulhasans/status
  verbs:
  - get
