---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apiserver.my.crd
  resources:
  - rokibulhasans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiserver.my.crd
  resources:
  - rokibulhasans/finalizers
  verbs:
  - update
- apiGroups:
  - apiserver.my.crd
  resources:
  - rokibulhasans/status
  verbs:
  - get
  - patch
  - update
